### ISSUE TITLE
Couldn't get the license card data

### ISSUE THREAD

**Issue by jegathesan** [Acuant/AcuantiOSMobileSDKV10#10]
Can't able to get the License (Australian) Data in iPod Touch(12.1) and iPhone 5s(11.2.1). Working fine in iPhone X, iPhone 6 Plus, iPhone 6. Seems the cropped the image resolution was small. I've tried to defined the **captureSession.sessionPreset = .photo** & **captureSession.sessionPreset = .high**, but no luck it doesn't give me a result. Even your sample application also not return the License Data 

Kindly provide me solution. Thanks

**Comment by vgargacuant** [comment]
Can you please raise a support ticket on https://support.acuantcorp.com regarding this issue? This way we can pull up your account and resolve the issue asap.

**Comment by jegathesan** [comment]
Resolved after using the [https://github.com/Acuant/AcuantiOSMobileSDKV10/commit/a8fdcfa059c78115c25b8c2882a63ebb12d4c222](commit).
