### ISSUE TITLE
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler

### ISSUE THREAD

**Issue by PatMurrayDEV** [Acuant/AcuantiOSMobileSDKV10#11]
Hi,

Can you please update the framework to be compiled again Swift 5 and Xcode 10.2?

Cheers

**Comment by monlyu** [comment]
still can't run back to 10.1

**Comment by TiagoLira** [comment]
I have the same problem, I need to keep two versions of Xcode for this. Please update it when possible.

**Comment by vgargacuant** [comment]
Thank you for your feedback. We are in the process of upgrading to Swift 5. We should have a release sometime next week.

**Comment by vgargacuant** [comment]
Please check out the following release which is compatible with Swift 5.
https://github.com/Acuant/AcuantiOSMobileSDKV10/releases/tag/10.0.1
