### ISSUE TITLE
Note : For running the framework in a simulator please use the framework in the folder Framework-For-Simulators

### ISSUE THREAD

**Issue by dekameron22** [Acuant/AcuantiOSMobileSDKV10#2]
Hello, I had a problem running this framework on Simulator

from this description is not really clear what should I do.

can you please explain better.

Thanks.

**Comment by tbehera** [comment]
Replace the AcuantMobileSDK.framework with the framework inside the folder **_Framework-For-Simulators_** to run in a simulator.

**Comment by tbehera** [comment]
@dekameron22 is this issue resolved?
