### ISSUE TITLE
Value of type 'Endpoints' has no member 'healthInsuranceEndpoint'

### ISSUE THREAD

**Issue by dekameron22** [Acuant/AcuantiOSMobileSDKV10#3]
`endPoints.healthInsuranceEndpoint` = "https://medicscan.acuant.net/api/v1"`

after I trying to set up endpoint for medical scanning, it throws me an error

and after I'm navigating to Endpoints class there is no property `healthInsuranceEndpoint`

**Comment by tbehera** [comment]
Please pull fresh and try again. Let me know if it fixes the issue.

**Comment by tbehera** [comment]
@dekameron22  Is this issue resolved?

**Comment by NithiTM** [comment]
What we need to give it for End point url(frmEndPoint, idEndPoint, healthInsuranceEndpoint) which url needs to give for that. Actually i want scan the License card and Insurance for that which url i need to give there
