### ISSUE TITLE
The class names in the SDK framework in the SampleApp aren't the same as the class names in the documentation

### ISSUE THREAD

**Issue by bwynne** [Acuant/AcuantiOSMobileSDKV10#5]
I went to the support website and pulled down the file named AssureID Connect iOS Mobile SDK API.  And the classnames referenced are not in the SampleApp codebase as far as I can tell.   We have received credentials and keys and still are getting an authorized error trying to plug them in the sample app, however in trying to debug it, it appears to be out of sync with the documentation?

**Comment by tbehera** [comment]
Is the GitHub documentation out of sync? Please specify which class name is missing.

**Comment by bwynne** [comment]
The documentation on the Acuant support website for the AssureID Connect iOS SDK refers to the following classes:
AcuantMobileSDKController
AcuantCardResult
AcuantError
AcuantCardProcessRequestOptions

etc.

**Comment by tbehera** [comment]
These classes are relevant to our older SDK which is another repository.Please follow the documentation in GitHub.

**Comment by bwynne** [comment]
Ok.  Thanks!
