### ISSUE TITLE
Integration Issues

### ISSUE THREAD

**Issue by marcmatta** [Acuant/AcuantiOSMobileSDKV10#7]
Hi,

We've been using the AcuantiOSMobileSDK for quite some time now and we're trying to move our project to Swift 4.2. Moving to this version of the SDK proved to be harder than anticipated. Can you please help with the following?

1.   Any Migration documentation we could use?
2.  Any plans to create a Pod for this version of the SDK?
3.  Also the documentation for this version isn't really elaborated.

Thank you in advance for your help! @tbehera

**Comment by tbehera** [comment]
1) There is no migration documentation as there is no one to one mapping between two SDKs.
2) No plans for a Pod
3) We will try our best to continuously improve the documentation.

**Comment by NithiTM** [comment]
I have download that V10 source code in GitHub when i try to run it. It encounters around 50 errors. Whether I have missed any files or what is the reason for those errors. Can you please explain me how to fix those errors.

**Comment by tbehera** [comment]
Are you trying to run in a Simulator or real device?
