### ISSUE TITLE
Error :- Could not get health card data

### ISSUE THREAD

**Issue by arasu01** [Acuant/AcuantiOSMobileSDKV10#8]
I have downloaded the sample, added the username, password and subscription id. 
Used the following end points:
```
        let endPoints = Endpoints()
        endPoints.idEndpoint = "https://services.assureid.net"
        endPoints.healthInsuranceEndpoint = "https://medicscan.acuant.net/api/v1"
```

I tried to scan insurance card using "Health Insurance card" option(PFA) in demo. it was giving me error after processing the image(PFA).

Could you please tell how to fix the issue.

![3 comprehealth epo](https://user-images.githubusercontent.com/6689319/47430585-7400da00-d7b7-11e8-9dae-904fbb8a8b67.png)

![screen shot 2018-10-24 at 6 04 19 pm](https://user-images.githubusercontent.com/6689319/47430563-63e8fa80-d7b7-11e8-8eda-1b3644b1c897.png)
![screen shot 2018-10-24 at 6 01 43 pm](https://user-images.githubusercontent.com/6689319/47430564-63e8fa80-d7b7-11e8-8f4f-c09509c1992c.png)

**Comment by tbehera** [comment]
@arasu01 Please provide us the name of the company so that we can check your credentials. You may also create a ticket at https://support.acuantcorp.com with the details.

**Comment by arasuyosi** [comment]
@tbehera : Thanks.

**Comment by arasu01** [comment]
@tbehera : Thanks
