### ISSUE TITLE
Universal SDK 

### ISSUE THREAD

**Issue by falkobuttler** [Acuant/AcuantiOSMobileSDKV10#9]
Are there any plans to release an universal SDK rather than one for device and one for simulator? This makes using this framework a pain and unnecessarily complicated because you constantly have to switch between two versions since Xcode doesn't support this out of the box.
This is also bad practice and against any best practices recommended by Apple and followed by any other major maintainer of frameworks for iOS applications.

**Comment by vgargacuant** [comment]
Thank you for your feedback. Please check the following release which provides framework FAT framework for Simulators and Devices.. 

https://github.com/Acuant/AcuantiOSMobileSDKV10/releases/tag/10.0.1
